Models/CalcModel.cs
namespace CalculatorWebApp.Models
{
    public class CalcModel
    {
        public double number1 { get; set; }
        public double number2 { get; set; }

        public double result { get; set; }
              


        public void Add()
        {
            //足し算
            this.result = number1 + number2;            
        }

        public void Subtrarct()
        {
            //引き算
            /*result = number1 - number2;
            return result;            
            */
            this.result = number1 - number2;            
        }
    

        public void Multiply()
        {
            //掛け算
            /*
            result = number1 * number2;
            return result;            
            */
            this.result = number1 * number2;
        }

        public void Divide()
        {
            if(number2 != 0)
            {
                //割り算
                /*
                result = number1 / number2;
                return result;
                */
                this.result = number1 / number2;
            }
            else
            {
                /*
                result = double.NaN;
                return result;
                */
                this.result = double.NaN;
            }
        }
    }
}

Models/ErrorViewModel.cs
namespace CalculatorWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CalcController.cs
using CalculatorWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.CompilerServices;

namespace CalculatorWebApp.Controllers
{
    public class CalcController : Controller
    {

        private readonly ILogger<CalcController> logger;

        private CalcModel calcModel;
       
        public CalcController(CalcModel calcModel, ILogger<CalcController> logger)
        {
            this.calcModel = calcModel;
            this.logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Calculate(string operation)
        {
            switch (operation)
            {
                case "Add":
                    
                    calcModel.Add();                    
                    
                    break;

                case "Subtract":
                    
                    
                    calcModel.Subtrarct(); 
                    break;

                case "Multiply":
                    
                    calcModel.Multiply();
                    break;

                case "Divide":
                    
                    
                    calcModel.Divide();
                    break;

                default: 
                    throw new NotImplementedException();                      
            }
            
            return View("Index", calcModel);
        }
    }
}

Controllers/HomeController.cs
using CalculatorWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CalculatorWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        
        public IActionResult CalcView()
        {
            return View();
        }
        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Calc/CalcView.cshtml
@model CalcModel
@{
    ViewData["Title"] = "Calculator";
}
<h1>@ViewData["Title"]</h1>

@using (Html.BeginForm("Calculate", "Calc", FormMethod.Post))
{
    <input asp-for="number1" placeholder="数値1" />
    <input asp-for="number2" placeholder="数値2" />

    <select name="operation">
        <option value = "Add">＋</option>
        <option value = "Subtract">－</option>
        <option value = "Multiply">×</option>
        <option value = "Divide">÷</option>
    </select>

    <input type="submit" value="計算" />
}

<input type="text" asp-for="result" readonly />

Views/Home/Index.cshtml
@model CalcModel
@{
    ViewData["Title"] = "Calculator";
}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<h1>@ViewData["Title"]</h1>

@using (Html.BeginForm("Calculate", "Calc", FormMethod.Post))
{
    <input asp-for="number1" placeholder="数値1" />
    <input asp-for="number2" placeholder="数値2" />

    <select name="operation">
        <option value="Add">＋</option>
        <option value="Subtract">－</option>
        <option value="Multiply">×</option>
        <option value="Divide">÷</option>
    </select>

    <input type="submit" value="計算" />
}

<input type="text" asp-for="result" readonly />

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CalculatorWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CalculatorWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CalculatorWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Calc">Calculate</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CalculatorWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>